#!/bin/bash

level=${1:-"1"}
if [[ $level -lt 1 || $level -gt 4 ]]; then
    echo "關卡請輸入 1-4！"
    exit -1
fi
echo "關卡 $level"
echo "請輸入您的正則表達式"
read -r regex

testcases_dir="testcase"

while IFS= read -r line; do
    line=$(echo -n "$line" | tr -d '\n')
    if [[ -n "$line" && ! $(echo "$line" | grep -E "^$regex$") ]]; then
        echo "Failed accept testcase: $line"
        exit 1
    fi
done < "$testcases_dir/$level.accept"


while IFS= read -r line; do
    line=$(echo -n "$line" | tr -d '\n')
    if [[ -n "$line" && $(echo "$line" | grep -E "^$regex$") ]]; then
        echo "Failed reject testcase: $line"
        exit 1
    fi
done < "$testcases_dir/$level.reject"

echo "All testcases passed"
if [[ $level -eq 2 ]]; then
    keyword="Rexcellenttt"
fi
if [[ $level -eq 3 ]]; then
    keyword="regexTra"
fi
if [[ $level -eq 4 ]]; then
    keyword="regexGod"
fi
if [[ -n $keyword ]]; then
    echo "Keyword: $keyword"
fi
